### PR TITLE
Configuring pyside and shiboken to build with Python 3

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey, thanks a lot for this one. Have you test it locally?

**Comment by nicoddemus** [comment]
Yes, I have tested it with Python 3.4, you can see the resulting conda packages [here](https://binstar.org/nicoddemus). :smile:

Cheers, :beers:

**Comment by ccordoba12** [comment]
Great!! Merging then!

**Comment by ccordoba12** [comment]
@goanpeca, you could use @nicoddemus packages for now ;-)

**Comment by nicoddemus** [comment]
Nice to know about [QtPy](https://github.com/goanpeca/QtPy). :smile:

**Comment by goanpeca** [comment]
:+1: great @nicoddemus :smile_cat:

**Pull request merged**
