### PR TITLE
Added python library search path to osx to enable boost-python compilation on OS X with Python 3

### PR DESCRIPTION
**Pull request by inati**

### CODE REVIEW

**Comment by frol** [comment]
It is wierd. It was me, who added Python 3 support to boost conda package and it compiled fine on Linux and Mac OS Python 2 and 3 with gcc-5 and clang.

BTW, I don't see any problem in setting `--with-python-root` explicitly. I'm just wondering why it worked for me.

Looks good to me!

**Comment by ccordoba12** [comment]
I'll take a look at this one next week :-)

**Comment by inati** [comment]
@ccordoba12 have you had a chance to look at this yet?

**Comment by ccordoba12** [comment]
Merging. I'll test it on my side when building the packages on OS X :-)

**Pull request merged**
