### PR TITLE
Fix SimpleITK build script for windows

### PR DESCRIPTION
**Pull request by blowekamp**
Update SimpleITK hash, with CMake build fixes for EXAMPLES, and an escape
sequence issue.

Use internal third party libraries on windows since depencent dll aren't automatically
include in the path at run-time. See:
https://groups.google.com/a/continuum.io/forum/#!topic/conda/wnRbABPq4hE

Use CONDA_PY for python version, as PY_VER is not being defined.

### CODE REVIEW

**Comment by asmeurer** [comment]
PY_VER not being defined sounds like a bug in conda-build. You shouldn't rely on CONDA_PY being defined as I don't think it is if you use `conda build --py 2.7`.

**Comment by blowekamp** [comment]
OK, I'll revert that change. I  "set CONDA_PY=34" then "conda build simpleitk" and PY_VER was not set. Resulting in a linking error.

Related on linux/osx I am setting the python library to:
"PYTHON_LIBRARY:FILEPATH=$PREFIX/lib/libpython${MY_PY_VER}.${SO_EXT}" 

Where MY_PY_VER adds the "m" character suffix for python 3. I don't recall what this library suffix means but it might be good to have it accessible in the build environment somehow.

**Comment by asmeurer** [comment]
From my reading of the conda-build code `PY_VER` should always be set. I just made a test recipe and it was set in there.

**Comment by asmeurer** [comment]
Oh this is Windows. I wonder if that is related. Let me check.

**Comment by asmeurer** [comment]
No, it works for me in Windows too.

**Comment by asmeurer** [comment]
I see the problem. It is `libpython33.lib`, but `PY_VER` is `3.3` (with the `.`).

**Comment by blowekamp** [comment]
That sounds right. I didn't recall that correctly away from the computer. 

BTW, the build that was hanging at scipy was caused by ez_setup using an old version of curl or wget on rh5 which hung with the requested http ssl connection. No longer using ez setup as suggested.

**Comment by asmeurer** [comment]
I don't remember the build hanging at scipy. It just took a really long time, and too much memory for my VM.

**Comment by blowekamp** [comment]
OK, Is there a suggestions for this line:

 -D "PYTHON_LIBRARY:FILEPATH=%PREFIX%/libs/python%CONDA_PY%.lib" ^

Or a robust where to specify the python library to use?  I think I can find an arcane batch command to remove the "." for PY_VER, just  checking if there is a better recommendation.

Thanks.

**Comment by asmeurer** [comment]
I think `%PY_VER:.=% will remove it. See http://www.dostips.com/DtTipsStringManipulation.php#Snippets.Replace

**Comment by blowekamp** [comment]
Thank you that did the trick.

**Pull request closed without merging**
