### PR TITLE
Move all python packages to a new (root-level) python directory

### PR DESCRIPTION
**Pull request by kalefranz**
This is an initial commit to move python packages out of the root directory for this repo.  Please comment if you see anything that obviously doesn't belong...

More long-term, the root will be reserved for package groupings (like what `r-packages` is now), and we'll continue to refactor into logical groupings.

### CODE REVIEW

**Comment by kalefranz** [comment]
@ilanschnell, @groutr, @msarahan One of you mind approving and merging?

**Comment by ilanschnell** [comment]
Did you make sure this doesn't break any existing PRs?

**Comment by kalefranz** [comment]
I went through the PRs since September and merged any that easily could be.  Anything left is still somehow controversial and under discussion or in progress.

**Comment by ccordoba12** [comment]
It's not possible to see the contents of this PR through Github, but if there are errors they should be easy to fix.

Besides, I think it's better to merge this now before merge conflicts start to appear.

**Comment by ccordoba12** [comment]
The only recipes that were left are `ipython-notebook` and `ipython-console`. Should we move or remove them?

The thing is those recipes are for the old IPython packages (i.e. before IPython was split into Jupyter).

**Comment by ccordoba12** [comment]
Also `python-patch` was left, but it's too old, so we should probably remove it too.

**Comment by ilanschnell** [comment]
I agree, `python-patch` should be removed.

**Comment by ccordoba12** [comment]
And what about `ipython-{notebook, qtconsole}`?

**Comment by kalefranz** [comment]
I'm fine removing them all if everyone else is

**Comment by ccordoba12** [comment]
Done :-)

**Pull request merged**
