### PR TITLE
Add recipe for pylearn2

### PR DESCRIPTION
**Pull request by AlbertDeFusco**
Conda recipe for [lisa-lab/pylearn2](https://github.com/lisa-lab/pylearn2) at tag `stable-201601`. Known to work for linux64 and linux32.

### CODE REVIEW

**Comment by ilanschnell** [comment]
Hmm, doesn't work for me:
```
build.sh: line 3: 17589 Illegal instruction     $PYTHON setup.py install
```

**Comment by ilanschnell** [comment]
This was on Centos 5 (64-bit).

**Comment by AlbertDeFusco** [comment]
I haven't been able to reproduce this on my Centos 5 (64-bit) VM. I'm using conda-build 1.19.2. I did the same thing in the posix_ipc package. Does that one work?

These are the packages in my `_build` environment for pylearn2.

```
libgfortran               3.0                           0  
mkl                       11.3.1                        0  
numpy                     1.10.4                   py35_1  
openssl                   1.0.2g                        0  
pip                       8.1.0                    py35_0  
pylearn2                  0.1.dev0                  <pip>
python                    3.5.1                         0  
readline                  6.2                           2  
scipy                     0.17.0              np110py35_2  
setuptools                20.2.2                   py35_0  
sqlite                    3.9.2                         0  
theano                    0.7.0               np110py35_0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.0.5                         1  
zlib                      1.2.8                         0
```

**Comment by AlbertDeFusco** [comment]
see PR #651

**Pull request merged**
