### PR TITLE
Make sure that GDAL_DATA is set and still present in the package

### PR DESCRIPTION
**Pull request by tswicegood**
Fixes the issues described in https://github.com/ContinuumIO/anaconda-issues/issues/221.

### CODE REVIEW

**Comment by tswicegood** [comment]
@kpurdon do you mind giving this a whirl?  The test via `conda build` still fails because of https://github.com/conda/conda-build/issues/364, but it should work for you once you activate the environment.

**Comment by kpurdon** [comment]
@tswicegood i'll give it a whirl as soon as I can this week. Thanks for the quick work.

**Comment by kpurdon** [comment]
@tswicegood i'm having issues building on both ubuntu14.04 and osx10.10.2. I am able to build and install directly form GDAL source on both machines (no conda involved). We have a workaround in place so I have not been able to put any time into exploring the issues below. If there is anything obvious let me know and I can test again.

## ubuntu

```
+ make
(cd port; make)
make[1]: Entering directory `/opt/miniconda/conda-bld/work/gdal-1.11.2/port'
/bin/sh /opt/miniconda/conda-bld/work/gdal-1.11.2/libtool --mode=compile --tag=CXX g++ -g -O2 -DHAVE_SSE_AT_COMPILE_TIME  -Wall  -DOGR_ENABLED -I/opt/miniconda/conda-bld/work/gdal-1.11.2/port -I/opt/miniconda/envs/_build/include 	-I/opt/miniconda/envs/_build/include  -DHAVE_CURL -DHAVE_LIBZ -c -o cpl_conv.lo cpl_conv.cpp
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1581: /opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: preserve_args+= --tag CXX: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= g++: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -g: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -O2: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -DHAVE_SSE_AT_COMPILE_TIME: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -Wall: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -DOGR_ENABLED: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -I/opt/miniconda/conda-bld/work/gdal-1.11.2/port: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -I/opt/miniconda/envs/_build/include: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -I/opt/miniconda/envs/_build/include: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -DHAVE_CURL: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -DHAVE_LIBZ: not found
/opt/miniconda/conda-bld/work/gdal-1.11.2/libtool: 1: eval: base_compile+= -c: not found
libtool: compile: you must specify a compilation command
libtool: compile: Try `libtool --help --mode=compile' for more information.
make[1]: *** [cpl_conv.lo] Error 1
make[1]: Leaving directory `/opt/miniconda/conda-bld/work/gdal-1.11.2/port'
make: *** [port-target] Error 2
Command failed: /bin/bash -x -e /home/vagrant/conda-recipes/gdal/build.sh
```

## osx

```
...

libtool: compile:  g++ -arch x86_64 -DHAVE_SSE_AT_COMPILE_TIME -Wall -I ../mem -I ../vrt -I/Applications/Postgres.app/Contents/Versions/9.3/include -I/Applications/Postgres.app/Contents/Versions/9.3/include/postgresql/server -DPG_HAS_PQESCAPESTRINGCONN -I/Users/kpurdon/miniconda/conda-bld/work/gdal-1.11.2/port -I/Users/kpurdon/miniconda/conda-bld/work/gdal-1.11.2/gcore -I/Users/kpurdon/miniconda/conda-bld/work/gdal-1.11.2/alg -I/Users/kpurdon/miniconda/conda-bld/work/gdal-1.11.2/ogr -I/Users/kpurdon/miniconda/conda-bld/work/gdal-1.11.2/ogr/ogrsf_frmts -DOGR_ENABLED -I/Users/kpurdon/miniconda/conda-bld/work/gdal-1.11.2/port -I/Users/kpurdon/miniconda/envs/_build/include -c postgisrasterdataset.cpp  -fno-common -DPIC -o ../o/.libs/postgisrasterdataset.o
postgisrasterdataset.cpp:2948:36: error: no member named 'GetMetadataDomainList' in 'GDALDataset'; did you mean
      simply 'GetMetadataDomainList'?
    return BuildMetadataDomainList(GDALDataset::GetMetadataDomainList(),
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   GetMetadataDomainList
postgisrasterdataset.cpp:2946:30: note: 'GetMetadataDomainList' declared here
char **PostGISRasterDataset::GetMetadataDomainList()
                             ^
postgisrasterdataset.cpp:2948:12: error: use of undeclared identifier 'BuildMetadataDomainList'
    return BuildMetadataDomainList(GDALDataset::GetMetadataDomainList(),
           ^
postgisrasterdataset.cpp:3149:23: error: redefinition of 'CreateCopy' as different kind of symbol
PostGISRasterDataset::CreateCopy( CPL_UNUSED const char * pszFilename,
                      ^
./postgisraster.h:278:25: note: previous definition is here
    static GDALDataset* CreateCopy(const char *, GDALDataset *,
                        ^
postgisrasterdataset.cpp:3149:35: error: use of undeclared identifier 'CPL_UNUSED'
PostGISRasterDataset::CreateCopy( CPL_UNUSED const char * pszFilename,
                                  ^
postgisrasterdataset.cpp:3154:68: error: expected ';' after top level declarator
                                  CPL_UNUSED void * pProgressData )
                                                                   ^
                                                                   ;
5 errors generated.
make[2]: *** [../o/postgisrasterdataset.lo] Error 1
make[1]: *** [postgisraster-install-obj] Error 2
make: *** [frmts-target] Error 2
Command failed: /bin/bash -x -e /Users/kpurdon/projects/conda-recipes/gdal/build.sh
```

**Comment by tswicegood** [comment]
I didn't try compiling on ubuntu, so there might be something missing there for sure.  @ilanschnell does anything jump out at you here from this output?

**Comment by tswicegood** [comment]
Thanks for the merge, @ilanschnell.  Any idea on the issue that @kpurdon was running into?

**Comment by mattexx** [comment]
+1 on the issue in Ubuntu. This might be a clue: https://www.gnu.org/software/automake/faq/autotools-faq.html#libtool-fails-with-_0022X_002d_002dtag_003dCXX-command-not-found_0022

**Comment by aleksandervines** [comment]
@kpurdon @mattexx 

I see this is an old post, and I guess you have figured out the issue on the building on ubuntu.

But I can inform that it is some issues with using sh instead of bash.

Running this command to replace /bin/sh with /bin/bash before configuring on ubuntu will solve the issue where += is not a valid sh syntax.

sed -i 's/\/bin\/sh/\/bin\/bash/g' configure

**Pull request merged**
