### PR TITLE
added recipe for sklearn2pmml

### PR DESCRIPTION
**Pull request by curtisalexander**
Adding a recipe for sklearn2pmml.

https://github.com/jpmml/sklearn2pmml

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for your contribution. This needs to go into the `python` subdirectory.

**Comment by ccordoba12** [comment]
Of the conda-recipes root directory, I mean ;-)

**Comment by curtisalexander** [comment]
Sorry for the mixup.  I closed the PR and deleted the branch.

**Comment by ccordoba12** [comment]
Well, there was no need to do that :-) You just needed to move the `sklearn2pmml` to `python`.

**Comment by curtisalexander** [comment]
Thanks for the kind corrections.  :-)  I'm definitely new with this whole fork / submit a PR thing.  Unfortunately I'm using the git working model "burn it to the ground and try again".  i'll submit another PR shortly.

**Comment by ccordoba12** [comment]
Ok, no problem ;-)

**Comment by curtisalexander** [comment]
Again, sorry for cluttering up the repo.  I submitted a second PR at conda/conda-recipes#614.

**Comment by ccordoba12** [comment]
Don't worry about it. We moved to use subdirectories for different languages just last month :-)

**Pull request closed without merging**
