### PR TITLE
Add missing GCC libraries to libgcc (Java, Objective-C)

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by asmeurer** [comment]
These are really big files. If these are really needed, we should probably use a separate package.

**Comment by ccordoba12** [comment]
I also think they should be added to a different package. They are not really necessary for C/C++ programs.

**Comment by jakirkham** [comment]
Unfortunately, separating them is not really feasible as they are all linked to `libgcc_s.1.dylib` or on linux  `libgcc_s.so.1`.

**Comment by asmeurer** [comment]
The other package could depend on libgcc.

**Comment by jakirkham** [comment]
Ok, we could do it that way. As a thought, it would also be reasonable to split out `libgfortran` as it isn't really a required C/C++ library.

**Comment by asmeurer** [comment]
gfortran is a very common dependency (in the case of OS X, it's the one library that isn't already part of the system). I think it's valuable to leave it in here.

**Comment by ccordoba12** [comment]
@asmeurer, should we close this one then?

**Comment by jakirkham** [comment]
Yeah, I'll open two new ones.

**Pull request closed without merging**
