### PR TITLE
Need pkg-config to build cairo

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by ccordoba12** [comment]
Is `pkg-config` needed in Mac too? If not, please make a dependency only for Linux

**Comment by jakirkham** [comment]
Unfortunately, yes, it is needed for Mac too.

**Comment by ccordoba12** [comment]
That's fine, I was just checking :-)

**Comment by jakirkham** [comment]
Completely understand. I appreciate the vigilance.

**Pull request merged**
