### PR TITLE
Upgraded prettyplotlib to v1.7

### PR DESCRIPTION
**Pull request by ovz**

### CODE REVIEW

**Comment by ccordoba12** [comment]
I think prettyplotlib is unmaintained now, right?

**Comment by ovz** [comment]
I still have ipython notebooks that use it. Would be convenient to keep last stable version as a conda package. WBR Oleg Zhylin ovz@yahoo.com 

     On Monday, February 2, 2015 12:17 PM, Carlos Cordoba <notifications@github.com> wrote:
   

 I think prettyplotlib is unmaintained now, right?—

**Comment by ccordoba12** [comment]
If prettyplotlib is pip installable and is a pure Python package, I'd be in favor of removing it from conda-recipes.

@asmeurer, @olgabot what do you think?

**Comment by ccordoba12** [comment]
The package is no longer maintained (as @olgabot mentioned), and it's easily pip-installable (as I already verified).

Now that pip is part of every conda environment, I don't see the need to maintain this recipe as part of conda-recipes.

**Comment by asmeurer** [comment]
It's useful to have recipes for pure Python packages (most recipes here are), but I agree we don't need to have recipes for dead projects.

**Comment by ccordoba12** [comment]
@asmeurer, I understand. My main reason was really that the project is dead now, but easily installable by other means.

**Pull request closed without merging**
