### PR TITLE
adding various r-packages

### PR DESCRIPTION
**Pull request by quasiben**
cc @mingwandroid

### CODE REVIEW

**Comment by mingwandroid** [comment]
We shouldn't see any .template files here, conda-build autogenerated those, I guess you got them from downloaded packages' info dirs?

Can you use `conda-skeleton cran` to make the recipes instead (though you need to change the case of various license families after unfortunately).

Also, I see various packages depending on `r`, they should depend on `r-base` instead and any other packages they happen to depend upon. It seems those packages were hand-crafted, perhaps?

The reason I'm need to be picky about this is that when I update to the latest releases, I use `conda skeleton cran` to generate new ones and then eyeball every single package for differences and I need that to be as easy as possible since there are now ~300 packages.

**Comment by quasiben** [comment]
@mingwandroid pulled from cran and rebased

**Comment by mingwandroid** [comment]
I built and uploaded all of these now.

**Comment by quasiben** [comment]
thanks @mingwandroid !

**Pull request merged**
