### PR TITLE
imageio v1.2

### PR DESCRIPTION
**Pull request by almarklein**
I was wondering, of all the packages in this list, which one are actually build by Continuum, and how is that decided?

### CODE REVIEW

**Comment by asmeurer** [comment]
There's a little more involved getting a package in the official channels, so it's based on popularity of the request, or if a customer requests a package. If you want something included, though, just ping @ilanschnell.

**Comment by ccordoba12** [comment]
Seems simple enough, merging :-)

**Comment by almarklein** [comment]
Well, I build imageio conda packages myself for py3k (which is me launching 5 different VM's), and then someone asked for one on Python 2.7. He proposed to automate building the packages via Travis + Appveyor, which is certainly an option, but if it would be in the official channels, that would be even easier :)

@ilanschnell Would imageio be popular enough (currently 3k downloads per month on Pypi) to be considered for inclusion?

**Comment by ilanschnell** [comment]
Yes, definitely.  I think at one point we already considered imageio, but had trouble building packages on some platforms.

**Pull request merged**
