### PR TITLE
libxml2: update to 2.9.3

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks.  Can you please explain the gcc inclusion?  Why is it only a build-time dependency? (no libgcc?)

**Comment by jschueller** [comment]
Yeah, I figured all compiled packages should be compiled with the same compiler. Plus I had to build on an older box (Debian Squeeze) to link against an older libc for users of old distros to be able to use my packages. I didn't set the libgcc dependency as it should be a dependency of the zlib recipe, so no need to pull it twice.

**Comment by msarahan** [comment]
Please add the libgcc dependency.  Explicit is better than implicit, in case libgcc is ever removed from zlib.

**Comment by jschueller** [comment]
@msarahan, ok

**Comment by msarahan** [comment]
Thanks!

**Pull request merged**
