### PR TITLE
OpenBabel recipe - tested on Mac OS X and Ubuntu

### PR DESCRIPTION
**Pull request by rwest**
**update:** 
I think this is now working on Mac OS X and Ubuntu

---
**original summary:**
I've tested this on MacOS X, but I feel it ought to work on linux too.
Mac binary is at https://binstar.org/rwest/openbabel

I took a few patches from the HomeBrew recipe, and an additional one to fix a failing unit test.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please test it on Linux and let us know when it's working to merge it :-)

**Comment by patrickfuller** [comment]
Thanks for taking the time to do this! It would be great to get this working, so I'm happy to help.

I made clean envs to try the build. Below is a dump of linux errors, and (if you can't immediately resolve) I'll try to look into them tomorrow. 

Linux (Ubuntu 14.04) - builds fine but doesn't run. Error from command line:

```
▶ obabel -H
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!
```

Error from python (opaquely hiding the above error):

```
▶ python
Python 2.7.9 |Continuum Analytics, Inc.| (default, Apr 14 2015, 12:54:25)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
>>> import pybel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrick/miniconda3/envs/rmg-babel-27/lib/python2.7/site-packages/pybel.py", line 69, in <module>
    informats = _formatstodict(_obconv.GetSupportedInputFormat())
  File "/home/patrick/miniconda3/envs/rmg-babel-27/lib/python2.7/site-packages/pybel.py", line 65, in _formatstodict
    broken = [(x,y.strip()) for x,y in broken]
ValueError: need more than 1 value to unpack
```

Small fixes:
 * Only supports Python 2, but pybel is 2/3 compatible
 * Mac - I don't think there's an official mac cairo to build off of. I linked to my homebrew lib, but it took away from the simplicity of a one-line install.

**Comment by rwest** [comment]
Thanks. 

Last things first: cairo is a bit of a pain and I still haven't managed to build all its mac dependencies myself. I have, however, been able to find binaries for the ones I couldn't build on binstar, so if you add my channel (rwest) to your `~/.condarc`, eg. something like
```
channels:
  - defaults
  - rmg
  - rwest
```
then it *should* be able to find cairo and all its parts. :pray:
Yes, it'd be nice to have working recipes for them all, and make them all official.

**Comment by ccordoba12** [comment]
@rwest, what cairo dependencies are missing on Mac?

**Comment by rwest** [comment]
Going off notes and memory here (I'm away from the relevant computer): I couldn't build [fontconfig](https://github.com/conda/conda-recipes/tree/master/fontconfig) or py2babel. I got binaries from @vgauthier's binstar channel though, so maybe he has working recipes.
My attempts are at https://github.com/ReactionMechanismGenerator/conda-recipes/tree/cairo

**Comment by connie** [comment]
@patrickfuller I am now running into the same error as you after finally being able to compile the python bindings.  

The import is failing because of this:

    import openbabel as ob
    _obconv = ob.OBConversion()
    _obconv.GetSupportedInputFormat()
  
Returns ` ('ops',)`.  However a real build of openbabel returns a full list of formats instead (see below), thus the pybel function is failing because this build returns a malformed list of supported input formats.

    ('acr -- ACR format', 'adfout -- ADF output format', 'alc -- Alchemy format', 'arc -- Accelrys/MSI Biosym/Insight II CAR format', 'bgf -- MSI BGF format', 'box -- Dock 3.5 Box format', 'bs -- Ball and Stick format', ....... )

This means something is still going wrong with the openbabel build somehow...

**Comment by patrickfuller** [comment]
@connie I quickly scanned this last night, and that error led me to `LoadAllPlugins` in `src/plugins.cpp`. It's looking for `data/plugindefines.txt` but can't find it. My guesses are either a compile-time path is messed up, or you may need to include the `data` folder with the build.

**Comment by rwest** [comment]
That may be a different problem, but it's the same symptom as I was having on MacOS X, i.e. that the python binding returning `('ops',)` and crashing, instead of a correct list of loaded modules.   This was my issue https://github.com/conda/conda-recipes/issues/309, but in brief: if I set `export BABEL_LIBDIR=/Users/rwest/anaconda/envs/_test/lib/openbabel/2.3.2` (or wherever appropriate) before testing then it would find all the libraries and `import pybel` would work. I then discovered that the default, if the environment variable `BABEL_LIBDIR` is not defined, is `OB_MODULE_PATH` which is defined in `/include/openbabel/babelconfig.h` which is created by cmake from  `src/config.h.cmake`, and already included the correct compile-time prefix path. The trouble was, once it was compiled into the binaries, it wasn't being corrected to the run-time path. For me, adding  `detect_binary_files_with_prefix: true` to the `build:` section of `meta.yaml` did the trick, and the compiled binaries then had the paths corrected. But you already have that change... Might it be that the auto-detect is not working and one needs to manually specify which binaries to "fix"?  Or it might be something else entirely. :shrug:

**Comment by connie** [comment]
Yes, when I set the `BABEL_LIBDIR` to `/home/connie/anaconda/lib/openbabel/2.3.2` I can also import pybel just fine and loads all of the file formats.  So I guess it does have something to do with the `detect_binary_files_with_prefix` not working properly.

**Comment by patrickfuller** [comment]
This probably doesn't solve the problem, but have you thought of using a more recent open babel commit? Something like this in your `meta.yaml`:

```
package:
    name: openbabel
    version: 2.3.90

source:
    fn: f3b13e77.tar.gz
    url: https://github.com/openbabel/openbabel/archive/f3b13e77.tar.gz [unix]
    sha1: 310d36ea31adc502c1272158337f93b08a56ba01
```

I tried building it through conda, and it works on mac but segfaults on linux.

**Comment by rwest** [comment]
Good idea @patrickfuller, will try that later.

Strange thing is, I'm now having the same problem on Mac as @connie is on Ubuntu. I wonder if I had accidentally left my `$BABEL_LIBDIR` defined when I previously thought it was working.

The symptom is, when importing pybel in python, or else when just running `obabel -L formats` from bash, I get a lot of these errors:
```
==============================
*** Open Babel Error  in openLib
  /Users/rwest/anaconda/envs/_test/lib/openbabel/2.3.2 did not load properly.
 Error: dlopen(/Users/rwest/anaconda/envs/_test/lib/openbabel/2.3.2, 9): no suitable image found.  Did find:
	/Users/rwest/anaconda/envs/_test/lib/openbabel/2.3.2: not a file
``` 

Looking at how the format loading code works (split between `OBConversion::LoadFormatFiles()` in `obconversion.cpp` and various functions in `dlhandler_unix.cpp`), it first figures out what directory to look in, (either `$BABEL_LIBDIR` if defined, or else some hard-coded path which conda-install should be taking care of fixing - see below), then searches that directory for `.so` files, then tries to load them all. 

When setting $BABEL_LIBDIR it works for me. When I don't it gives the same number of errors as there are `.so` files inside that directory, suggesting the first stages (finding the folder and looking inside it for files) is working, but the loading is failing. The loading error messages all say they're trying to load the *directory*, not the files inside the directory. 
Then, referring to how conda-build [makes packages relocatable](http://conda.pydata.org/docs/build.html#making-packages-relocatable):

> The registered files will have their build prefix replaced with the install prefix at install time. This works by padding the install prefix with null terminators, such that the length of the binary file remains the same.

My hypothesis is that the filenames it's trying to load are something like:
`/Users/rwest/anaconda/envs/_test/lib/openbabel/2.3.2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\/abinitformat.so`  etc.

Now to figure out how to fix it, and see if I'm right.

**Comment by connie** [comment]
Even after your most recent commits I'm still running into the following error:

    ===== testing package: openbabel-2.3.2-py27_3 =====
    import: u'openbabel'
    import: u'pybel'
    running run_test.py
    ==============================
    *** Open Babel Warning  in Init
      Cannot initialize database
    ==============================
    *** Open Babel Warning  in Init
      Cannot initialize database
    ==============================
    *** Open Babel Warning  in Init
      Cannot initialize database
    this is shit
    ==============================
    *** Open Babel Warning  in InChI code
      #0 :Unknown element(s):
    ==============================
    *** Open Babel Error  in InChI code
      InChI generation failed
    ==============================
    *** Open Babel Warning  in InChI code
      #0 :Unknown element(s):
    ==============================
    *** Open Babel Error  in InChI code
      InChI generation failed
    ==============================
    *** Open Babel Warning  in InChI code
      #0 :Unknown element(s):
    ==============================
    *** Open Babel Error  in InChI code
      InChI generation failed
    Traceback (most recent call last):
      File "/home/connie/anaconda/conda-bld/test-tmp_dir/run_test.py", line 46, in <module>
        canonicals = [pybel.readstring("inchi", inchi).write("can").strip() for inchi in inchis]
      File "/home/connie/anaconda/envs/_test/lib/python2.7/site-packages/pybel.py", line 189, in readstring
        string, format))
    IOError: Failed to convert '' to format 'inchi'

If the `BABEL_DATADIR` variable is set to `/home/connie/anaconda/share/openbabel/2.3.2` this error disappears.  So it seems very similar to the previous problem.

**Comment by connie** [comment]
Wonderful.  It looks like it also compiled correctly on Linux after these commits (with only slight modifications).

**Comment by rwest** [comment]
I think this is now working for both me (Mac) and @connie (Ubuntu). Would anyone else care to test it? or review what we've come up with?

**Comment by patrickfuller** [comment]
Tested on linux with `conda install -c connie openbabel`, and that works. Mac with `conda install -c rwest openbabel`, and there's a slight bug. I think you need to rename [this line](https://github.com/conda/conda-recipes/pull/310/files#diff-261bd5033ad1a3909de1164f32521dfcR26) in the meta.yaml from `pkg-config` to `pkgconfig`.

Is there interest in pushing two versions of the binaries? Your project might want to fix openbabel to 2.3.2 for stability, but that release is a couple of years old at this point. I think many conda/openbabel users want something closer to master. We could even convert the patches into a pull request, and then link to that version.

**Comment by patrickfuller** [comment]
It also looks like @Clyde-fare managed to create an openbabel binary without patching ([binstar](https://binstar.org/search?q=openbabel)). I think that's the better approach if it works cross platform.

**Comment by connie** [comment]
I believe his binary does not come with the python bindings.

On Mon, Jun 1, 2015 at 10:02 AM, Patrick Fuller <notifications@github.com>
wrote:

> It also looks like @Clyde-fare <https://github.com/Clyde-fare> managed to
> create an openbabel binary without patching (binstar
> <https://binstar.org/search?q=openbabel>). I think that's the better
> approach if it works cross platform.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda-recipes/pull/310#issuecomment-107499312>.
>



-- 
Connie Gao
connieg@mit.edu || homepage <http://www.conniegao.com> || 978-500-5197
Chemical Engineering PhD Candidate
Massachusetts Institute of Technology

**Comment by patrickfuller** [comment]
It seems to work for me, although I haven't tested it outside of importing pybel. Here's his build.sh:

```
cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_GUI=OFF -DPYTHON_BINDINGS=ON -DPYTHON_LIBRARY=$PREFIX/lib/libpython${PY_VER}.so -DPYTHON_INCLUDE_DIR=$PREFIX/include/python${PY_VER} -DPYTHON_EXECUTABLE=$PYTHON -DRUN_SWIG=TRUE
make -j2
make install
```

The only difference I can see is the `BUILD_GUI` flag, but it does compile and run on my linux computer.

**Comment by connie** [comment]
I tried Clyde-Fare's binary just now and import pybel fails with the old error:

    >>> import pybel
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/connie/anaconda/lib/python2.7/site-packages/pybel.py", line 69, in <module>
        informats = _formatstodict(_obconv.GetSupportedInputFormat())
      File "/home/connie/anaconda/lib/python2.7/site-packages/pybel.py", line 65, in _formatstodict
        broken = [(x,y.strip()) for x,y in broken]
    ValueError: need more than 1 value to unpack

Not sure why it's behaving differently for us.

**Comment by patrickfuller** [comment]
I think your behavior is correct. Looking into it, I think `conda install -c Clyde_Fare openbabel` in a new environment just linked yours. I deleted all the caches open babels and now I'm getting the old error back.

**Comment by ccordoba12** [comment]
So is this ready to merge it?

**Comment by rwest** [comment]
@patrickfuller suggested changing `pkg-config` to `pkgconfig`. 
Sounds reasonable, but it seems that for whatever reason all my testing was with the `pkg-config` package from @asmeurer's channel (pkg-config-0.28-1.tar.bz2) rather than the `pkgconfig` on the defaults channel (pkgconfig-1.1.0-py27_0.tar.bz2 etc).

Not sure why both packages exist or what the difference is. I probably just searched for pkg-config when I first needed it, and didn't think to look for the other.

I'll make the change and test it again (on Mac at least).
Otherwise, I believe it's ready.

**Comment by ccordoba12** [comment]
@rwest, thanks for the update.

**Comment by rwest** [comment]
I should have googled before writing "I'm not sure why both packages exist or what the difference is":
 * pkg-config is the actual `pkg-config` program, which is usually installed on linux but may not be and is not by default on a clean Mac
 * pkgconfig is the python module to interact with `pkg-config`, and if you try using it without `pkg-config` itself then it errors like this:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rwest/anaconda/envs/_test/lib/python2.7/site-packages/pkgconfig/pkgconfig.py", line 112, in installed
    if not exists(package):
  File "/Users/rwest/anaconda/envs/_test/lib/python2.7/site-packages/pkgconfig/pkgconfig.py", line 58, in _wrapper
    raise EnvironmentError("pkg-config is not installed")
EnvironmentError: pkg-config is not installed
```

For me, pkg-config gets installed anyway even if removed from this deps list, because cario needs it (at least the mac cairo I have). But if I remove cario and force it to run without pkg-config, openbabel build fails like this:
```
CMake Error at /Users/rwest/anaconda/envs/_build_placehold_placehold_placehold_placehold_placeh/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```
Therefore I conclude that the recipe needs `pkg-config` and not `pkgconfig` and I think it is **ready to merge** (unless you'd like me to rebase it and tidy the history? not sure if you prefer clean PRs or honest histories)

(Someone can open a new PR to add Windows support!)

**Comment by ccordoba12** [comment]
I prefer honest history, so I'm merging it :-)

Thanks for your contribution!

**Comment by patrickfuller** [comment]
@rwest @connie Thanks for putting this script together!

For what it's worth, I used this to build a recent openbabel commit ([binstar link](https://binstar.org/patrickfuller/openbabel)). Can be installed with `conda install -c patrickfuller openbabel`, and with rwest and asmeurer channels added.

**Pull request merged**
