### PR TITLE
MSYS2 and R-Language 3.2.4 packages.

### PR DESCRIPTION
**Pull request by mingwandroid**
Ping @groutr, @msarahan, @ocefpaf

3.2.5 is incoming - they renamed 3.2.4-revised to 3.2.5 like they should've done in the first place - but this (minus r-gsw, r-oce, r-seacarb) is what was released for Windows already so we should have a commit for it.

Note I'm using Anatoly Techtonik's patch.py too, IMHO we should aim to use this for all of our patching. It might take a small amount of work to test with all of our patches and to fix it up, but not spawning out to a weird, old gnuwin32 patch on Windows and some different, random versions of gnu patch on Unix seems preferable to me.

### CODE REVIEW

**Comment by daler** [comment]
Hi, thanks so much for working on this. [R 3.3.0 was released on May 3](https://www.r-project.org/), and several core Bioconductor tools now depend on 3.3.0. Are there plans for R 3.3.0 after this 3.2.5 PR?

(ping @bgruening)

**Comment by mingwandroid** [comment]
I will try to build R 3.3.0 for Windows as soon as I can, hopefully within a week.

**Comment by daler** [comment]
Great -- thank you.

**Comment by daler** [comment]
Hi @mingwandroid - while this PR has been merged, I don't see R 3.3.0 in the R conda channel. Is it in another channel else? Or is it waiting on the windows build? Thanks.

**Pull request merged**
