### PR TITLE
libtiff: Fix jpeg dependency, add lzma dependency, upgrade to 4.0.6

### PR DESCRIPTION
**Pull request by stuarteberg**
The `libtiff` recipe has some problems, which are also affecting official Anaconda `libtiff` package.

1. Support for jpeg compression is broken.  Yes, `jpeg` was listed as a dependency in `meta.yaml`, but `build.sh` did not provide the `--with-jpeg-...` options.  (Apparently libtiff's `configure` script is not smart enough to find `libjpeg` on it's own.)

    When jpeg is properly specified, you'll notice that `libjpeg` is actually referenced in `libtiff.dylib`:

    ```
    $ otool -L /miniconda/envs/_build/lib/libtiff.dylib 
    /miniconda/envs/_build/lib/libtiff.dylib:
    	@rpath/./libtiff.5.dylib (compatibility version 8.0.0, current version 8.4.0)
    	@rpath/liblzma.5.dylib (compatibility version 6.0.0, current version 6.5.0)
    	@rpath/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
    	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
    ```

    ... whereas `libjpeg` is not referenced at all in Anaconda's current `libtiff.dylib` package.

2. libtiff can be configured to support `lzma` compression, but we weren't enabling it.  Since lzma is now included as a dependency of `python` itself (for python 3, anyway), I figured there was little harm in adding it as a dependency of `libtiff` -- most users will already have it installed.

3. For some reason, `zlib` was listed as a `build` dependency, but not a `run` dependency.  Now I've added it to the `run` requirements.  If that was the wrong thing to do for some reason, let me know.

4.  The `conda-recipes/libtiff` was still using version 4.0.2, even though the Anaconda distro has upgraded to 4.0.6 by now.  I updated this recipe to 4.0.6, too.  (And I set `build:number` to `1`, so this recipe can be immediately applied to the "official" Anaconda distro.)

This PR addresses all of the above.  I have built it on Mac and Linux.  Example binaries available via: `conda install -c stuarteberg libtiff`

**Note:** I did not test on Windows, nor did I update the windows `bld.bat` file.  I did, however, verify that the patch in this recipe still applies cleanly in the libtiff 4.0.6 source code.

### CODE REVIEW

**Comment by stuarteberg** [comment]
Once this PR is accepted, I would greatly appreciate it if the official Anaconda package repo were updated, too.

**Comment by msarahan** [comment]
Thanks for this.  We are putting out fires from the installation right now.  If I do not get to this by the end of next week, please ping me.

**Comment by stuarteberg** [comment]
Besides support for `jpeg` and `lzma`, `libtiff` can also include support for `jbig`, if available.  Anaconda doesn't have a `jbig` package yet, so I just implemented a PR to add it (#467).  If you're interested, I can now add `jbig` support to this `libtiff` PR. (I've already implemented it [in a branch](https://github.com/stuarteberg/conda-recipes/tree/libtiff-with-jbig/libtiff).)

Again, I didn't investigate Windows support, so the Windows `libtiff` package may be falling behind the Linux/Mac version.  But that seems like a bad reason to withhold improvements to the Linux/Mac package.

**Comment by msarahan** [comment]
Please go ahead with jbig support.  I'll do what I can to make it work on Windows.

**Comment by stuarteberg** [comment]
Also: Sorry, I didn't notice that @msarahan had already submitted a PR (#445) to upgrade the `libtiff` package to v4.0.6.  Now I've changed my PR here to cherry-pick from that PR instead of upgrading it myself.

**Comment by stuarteberg** [comment]
>Please go ahead with jbig support.

OK, pushed.  Also updated my packages on anaconda.org/stuarteberg (Mac and Linux only).

>I'll do what I can to make it work on Windows.

OK.  For now, this recipe excludes `jbig` on Windows.  So if you don't have time to deal with Windows support for `jbig` right now, you could accept these changes as-is without doing any harm:

```
requirements:
  build:
    - zlib
    - jpeg
    - xz   # provides liblzma
    - jbig # [not win]
```

**Comment by stuarteberg** [comment]
>>Please go ahead with jbig support.

>OK, pushed.

Just to point out the obvious: This PR is now dependent on #467, so merge that first...

**Comment by stuarteberg** [comment]
I'm rethinking this a bit.  I figured it couldn't hurt to add JBIG support because it is easily linked into libtiff, and somebody happend to ask me about it recently.  But after reading about what JBIG actually is, it doesn't sound very important.  Apparently, it's mostly used in fax machines.

I guess there's no harm in supporting it for the easy case (Mac/Linux), but we shouldn't feel bad about leaving Windows support out -- especially since it looks like there's no readily available Windows package for it.  I say don't bother.

**Comment by msarahan** [comment]
Thanks - updating the official recipe now.

**Comment by msarahan** [comment]
Official recipe has been updated.  Builds will show up as build number 1.  These may not be available until later this week.

I was not able to add these libraries to the Windows build.  The makefile included with libtiff offers no customization of libraries to link against.  Unfortunately, I don't have time to write a CMake build script for libtiff...

**Pull request merged**
