### PR TITLE
Updated openblas recipe

### PR DESCRIPTION
**Pull request by sdrobert**
- Updated build.sh for conda build 3
- Made dependency on libgfortran explicit
- Upgraded to Openblas v0.2.20

Some of this was influenced by conda-forge's recipe. Things appear to be linking properly based on my testing on osx and ubuntu, though some formal testing in the recipe is sorely lacking. Let me know what else might be needed.

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks!  CC @jjhelmus - he's working on our openblas stuff right now.  For your reference, this repo is deprecated.  You should instead submit PRs to https://github.com/AnacondaRecipes, which mimics conda-forge's structure and is made up mostly of forks from conda-forge.  One of us at Anaconda will need to fork the openblas recipe over if it isn't already, but then you can issue PRs against that feedstock repo.

**Comment by sdrobert** [comment]
Ah, sorry about that. There are actually two recipes there: openblas-recipe and openblas-feedstock. The feedstock is indeed the conda forge recipe, but, based on the format, it looks like openblas-recipe is what's in use now. I'll issue a PR there, then.

**Comment by jjhelmus** [comment]
I've been working on updating openblas for the Anaconda distribution if you want to have a look @sdrobert.  The branch I've been working on is https://github.com/AnacondaRecipes/openblas-feedstock/tree/jjh_nbs.  There are one or two commits that I have locally which I still need to push up.

**Comment by sdrobert** [comment]
@jjhelmus  Cool! It's a lot nicer than mine, though I've got a few points that are likely valuable. Would you like me to hold off (entirely or temporarily), submit a PR, or just talk here?

**Comment by jjhelmus** [comment]
I just pushed up the latest changes to the OpenBLAS recipes to the master branch of [AnacondaRecipes/openblas](https://github.com/AnacondaRecipes/openblas-feedstock).  I think it takes into account most of the changes from this PR and the updates that the conda-forge feedstock has.  

@sdrobert , feel free to open an issue or submit a PR to that repos if you see anything concerning or that can be improved.

**Pull request closed without merging**
