### PR TITLE
primesieve: Provide a python module that generates prime numbers fast.

### PR DESCRIPTION
**Pull request by jakirkham**
This is a python wrapper ( https://github.com/hickford/primesieve-python ) of this fast C++ primesieve implementation ( http://primesieve.org ).

Tested on both Mac OS 10.9 and CentOS 6.3.

Presumably works on Windows, but I don't have the right tools ATM.

### CODE REVIEW

**Comment by jakirkham** [comment]
Planning to change so it builds from the git repo and thus is able to run tests. Currently, python tests are not available in the PyPI package.

**Comment by jakirkham** [comment]
Alright. Fixed to use git. Runs tests during build. Ready to go.

**Comment by msarahan** [comment]
Do you mind cleaning up the extra comments here? Otherwise ready IMO.

**Comment by jakirkham** [comment]
Sure, I cleaned up the comments and rebased. Please let me know if there is anything else.

**Comment by msarahan** [comment]
LGTM. merging.

**Pull request merged**
