### PR TITLE
Enable MINC support in simpleitk build

### PR DESCRIPTION
**Pull request by gdevenyi**
This PR depends on the merging of https://github.com/SimpleITK/SimpleITK/pull/67 so that the options specified for SimpleITK are passed via the SuperBuild to ITK.

### CODE REVIEW

**Comment by blowekamp** [comment]
MINC is a popular image format and this is a useful feature to be able to enable for SimpleITK. However this ITK module has not been enable by default in ITK because there are a number of Valgrind memory defects that have not been addressed. We which to distribute a stable and reliable package,

Could this be turned into an option feature[1]? ( or the issues in ITK addressed? )

Thanks!

[1] http://conda.pydata.org/docs/building/meta-yaml.html#id1

**Comment by gdevenyi** [comment]
Hi @blowekamp,

Can you point me at the valgrind issues so I can inform the MINC maintainers of this?

As for converting to an option, that's doable, I'll have to figure that out.

Are you proposing I rebase against #701 ?

**Comment by blowekamp** [comment]
With the current ITK master, many of the tests are not even passing:

https://open.cdash.org/viewTest.php?onlyfailed&buildid=4545427

I only checked that after running valgrind:

https://open.cdash.org/viewDynamicAnalysis.php?buildid=4545685

**Comment by gdevenyi** [comment]
Thanks @blowekamp,

I've opened up an issue with libminc here https://github.com/BIC-MNI/libminc/issues/75

**Comment by gdevenyi** [comment]
Defaults on in ITK 5.0 now.

**Comment by blowekamp** [comment]
MINC was include in the SImpleITK [1.1 release](https://github.com/SimpleITK/SimpleITK/releases/tag/v1.1.0).

**Pull request closed without merging**
